freeze("$(PORT_DIR)/modules")
freeze("$(MPY_DIR)/tools", ("upip.py", "upip_utarfile.py"))
freeze("$(MPY_DIR)/ports/esp8266/modules", "ntptime.py")
freeze("$(MPY_DIR)/drivers/dht", "dht.py")
freeze("$(MPY_DIR)/drivers/onewire")
include("$(MPY_DIR)/extmod/uasyncio/manifest.py")
include("$(MPY_DIR)/extmod/webrepl/manifest.py")
freeze("../python_modules/campzone2019")
freeze("../python_modules/common", ("boot.py", "_buttons.py", "shell.py", "term.py", "virtualtimers.py", "wifi.py", "system.py", ))
freeze("../python_modules/common/tasks", ("powermanagement.py"))
freeze("../python_modules/common/umqtt")