#define MICROPY_HW_BOARD_NAME "ESP32 module"
#define MICROPY_HW_MCU_NAME "ESP32"

#ifdef CONFIG_BUS_VSPI_ENABLE
#define MICROPY_HW_SPI2_MOSI                CONFIG_PIN_NUM_VSPI_MOSI
#define MICROPY_HW_SPI2_MISO                CONFIG_PIN_NUM_VSPI_MISO
#define MICROPY_HW_SPI2_SCK                 CONFIG_PIN_NUM_VSPI_CLK
#endif

#ifdef CONFIG_BUS_HSPI_ENABLE
#define MICROPY_HW_SPI1_MOSI                CONFIG_PIN_NUM_HSPI_MOSI
#define MICROPY_HW_SPI1_MISO                CONFIG_PIN_NUM_HSPI_MISO
#define MICROPY_HW_SPI1_SCK                 CONFIG_PIN_NUM_HSPI_CLK
#endif
